# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 12:04
from __future__ import unicode_literals

from django.db import migrations


def create_group(apps, schema_editor):
    group = apps.get_model('auth', 'Group')
    group.objects.get_or_create(name='cine')


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0009_adresses'),
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_group),
    ]
