# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 13:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cine", "0010_create_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="film",
            name="duree",
        ),
    ]
