# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 13:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cine", "0011_remove_film_duree"),
    ]

    operations = [
        migrations.RenameField(
            model_name="film",
            old_name="duree_min",
            new_name="duree",
        ),
    ]
