# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0012_rename_duree_min_to_duree'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ['vu', 'titre']},
        ),
    ]
