# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 08:47
from __future__ import unicode_literals

import sortedm2m.fields

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cine', '0013_film_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinephile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.TextField()),
                ('soirees', models.ManyToManyField(to='cine.Soiree')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vetos', models.ManyToManyField(related_name='vetos', to='cine.Film')),
                ('votes', sortedm2m.fields.SortedManyToManyField(help_text=None, to='cine.Film')),
            ],
        ),
    ]
