# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 14:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cine", "0015_change_m2m_models"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adress",
            name="user",
        ),
        migrations.AlterUniqueTogether(
            name="dispotowatch",
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name="dispotowatch",
            name="cinephile",
        ),
        migrations.RemoveField(
            model_name="dispotowatch",
            name="soiree",
        ),
        migrations.AlterUniqueTogether(
            name="vote",
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name="vote",
            name="cinephile",
        ),
        migrations.RemoveField(
            model_name="vote",
            name="film",
        ),
        migrations.DeleteModel(
            name="Adress",
        ),
        migrations.DeleteModel(
            name="DispoToWatch",
        ),
        migrations.DeleteModel(
            name="Vote",
        ),
    ]
