# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 14:44
from __future__ import unicode_literals

from django.db import migrations, models

import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0016_rm_old_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinephile',
            name='adresse',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cinephile',
            name='soirees',
            field=models.ManyToManyField(blank=True, to='cine.Soiree'),
        ),
        migrations.AlterField(
            model_name='cinephile',
            name='vetos',
            field=models.ManyToManyField(blank=True, related_name='vetos', to='cine.Film'),
        ),
        migrations.AlterField(
            model_name='cinephile',
            name='votes',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='cine.Film'),
        ),
    ]
