# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0020_cinephiles_inactifs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cinephile',
            options={'ordering': ['user__username']},
        ),
    ]
