# Generated by Django 2.0 on 2017-12-06 00:32
from datetime import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def update_moment(apps, schema_editor):
    Soiree = apps.get_model('cine', 'Soiree')
    for soiree in Soiree.objects.all():
        soiree.moment = datetime.combine(soiree.date, soiree.time, tzinfo=timezone.tzinfo())
        soiree.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0023_auto_20170709_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='soiree',
            name='moment',
            field=models.DateTimeField(default=timezone.now),
            preserve_default=False,
        ),
        migrations.RunPython(update_moment),
        migrations.AlterModelOptions(
            name='soiree',
            options={'get_latest_by': 'moment', 'ordering': ['moment']},
        ),
        migrations.RemoveField(
            model_name='soiree',
            name='date',
        ),
        migrations.RemoveField(
            model_name='soiree',
            name='time',
        ),
        migrations.AddField(
            model_name='cinephile',
            name='pas_classes',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='soiree',
            name='hote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
