# Generated by Django 2.0 on 2017-12-06 00:43

from django.db import migrations

import autoslug.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0024_clean'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ['vu', 'name']},
        ),
        migrations.RenameField(
            model_name='film',
            old_name='titre',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='film',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True),
        ),
    ]
