# Generated by Django 2.0 on 2017-12-06 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0025_auto_20171206_0043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinephile',
            name='vetos',
        ),
        migrations.RemoveField(
            model_name='cinephile',
            name='votes',
        ),
    ]
