# Generated by Django 2.0 on 2017-12-06 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cine", "0026_auto_20171206_0047"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cinephile",
            old_name="pas_classes",
            new_name="should_vote",
        ),
    ]
