# Generated by Django 2.0.1 on 2018-01-28 19:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cine", "0028_auto_20180128_1914"),
    ]

    operations = [
        migrations.AddField(
            model_name="soiree",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="soiree",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
